### ISSUE TITLE
Takes more than 15 minutes to load 256 ports

### ISSUE THREAD

**Issue by mthapa3** [NeuronRobotics/nrjavaserial#10]
Hi,
   We are using nrjavaSerial-3.8.8 API on a Windows 64 bit environment with JDK 7 (64 bit).
We're using CommPortIdentifier.getPortIdentifiers()  to get a list of available ports. This method takes more than 15 minutes to load around 256 ports. 
Our server has more than 4000 virtual ports. Is there a better way or a work around to reduce the loading time?

Thanks.

**Comment by Ri5ux** [comment]
I have a Windows specific resolution for this if anyone is interested. Gets you a list of the available COM ports without having to scan them and wait for a response. Tested, confirmed working. https://gist.github.com/Ri5ux/bfe6a28f6680b82c30b8c920ade2a169

**Comment by madhephaestus** [comment]
@Ri5ux thats a cool trick, can you add it as a PR and ill make that eh standard method?

**Comment by Ri5ux** [comment]
@madhephaestus Sure, give me a couple days and I'll have a PR for you.
