### ISSUE TITLE
getting Could not initialize class gnu.io.RXTXCommDriver exception

### ISSUE THREAD

**Issue by RamiKhawaly** [NeuronRobotics/nrjavaserial#106]
i'm getting this error when running the code on my raspberrypi 2
what im missing. 
i followed all the instructions... 
anything more ?
i added it with maven dependency

**Comment by firasalmanna** [comment]
@mindoLife same here, did you find a solution?

**Comment by mindoLife** [comment]
No unfortunately we don't have any solution, in case we find i will update
here. and in case you find, please share it here.

**Comment by madhephaestus** [comment]
Try 5.0.2
