### ISSUE TITLE
Logging of native code

### ISSUE THREAD

**Issue by martinnaughton** [NeuronRobotics/nrjavaserial#12]
**Hi,**
**I am trying to debug a problem with connecting with a serial device.**

 A fatal error has been detected by the Java Runtime Environment:

  SIGILL (0x4) at pc=0xa9d0d3e2, pid=1408, tid=2841312064

 JRE version: Java(TM) SE Embedded Runtime Environment (7.0_55-b13) (build 1.7.0_55-b13)
 Java VM: Java HotSpot(TM) Embedded Client VM (24.55-b03 mixed mode linux-x86 )
 Problematic frame:
 C  [libNRJavaSerial.so+0x93e2]  check_group_uucp+0x72

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /home/root/hs_err_pid1408.log
[thread -1443280064 also had an error]

 If you would like to submit a bug report, please visit:
   http://bugreport.sun.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**From the full exception of the problem i got**
Stack: [0xaafec000,0xab03c000],  sp=0xab039a40,  free space=310k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libNRJavaSerial.so+0x93e2]  check_group_uucp+0x72

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  gnu.io.RXTXCommDriver.testRead(Ljava/lang/String;I)Z+0
j  gnu.io.RXTXCommDriver.registerValidPorts([Ljava/lang/String;[Ljava/lang/Strin
g;I)V+202
j  gnu.io.RXTXCommDriver.registerScannedPorts(I)V+1502
j  gnu.io.RXTXCommDriver.initialize()V+35
j  gnu.io.CommPortIdentifier.getPortIdentifiers()Ljava/util/Enumeration;+53
j  gnu.io.NativeResource.testNativeCode()V+0
j  gnu.io.NativeResource.inJarLoad(Ljava/lang/String;)V+37
j  gnu.io.NativeResource.loadLib(Ljava/lang/String;)V+54
j  gnu.io.NativeResource.load(Ljava/lang/String;)V+138
j  gnu.io.SerialManager.<init>()V+23
j  gnu.io.SerialManager.getInstance()Lgnu/io/SerialManager;+10
j  gnu.io.RXTXCommDriver.<clinit>()V+39
v  ~StubRoutines::call_stub
J 1772  java.lang.Class.forName0(Ljava/lang/String;ZLjava/lang/ClassLoader;)Ljav
a/lang/Class; (0 bytes) @ 0xb4ecc47b [0xb4ecc410+0x6b]
j  java.lang.Class.forName(Ljava/lang/String;)Ljava/lang/Class;+8
j  gnu.io.CommPortIdentifier.<clinit>()V+12
v  ~StubRoutines::call_stub
j  org.openhab.binding.zwave.internal.protocol.ZWaveController.connect(Ljava/lan
g/String;)V+13
j  org.openhab.binding.zwave.internal.protocol.ZWaveController.<init>(Ljava/lang
/String;)V+161
j  org.openhab.binding.zwave.internal.ZWaveActiveBinding.updated(Ljava/util/Dict
ionary;)V+65
j  org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run()V+8
j  org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run()V+15
v  ~StubRoutines::call_stub

**I have checked your code and in the SerialImp.check_group_uucp there is logging statements. When i get the JVM error it only shows that the problem was in the check_group_uucp method. Does not show the line in native C code that produced the problem or the log error. If i had that native logging i could debug my problem faster.**

**How do you turn on native code logging for nrjavaserial? I could add it to the Git Hub wiki once i have verified it worked.**

**Comment by madhephaestus** [comment]
stale closing
