### ISSUE TITLE
JVM Crash Windows Server 2016

### ISSUE THREAD

**Issue by hammo** [NeuronRobotics/nrjavaserial#122]
I'm using this with a ColdFusion eventgateway I wrote.  It works fine in windows 10.  I've re-built nrjavaserial.jar on the server (Windows server 2016).  It crashes the JVM when I try to read data from the port.  Any guidance would be appreciated.

# Problematic frame:
# C  [libNRJavaSerial.dll+0x70f5]

[hs_err_pid9628.log](https://github.com/NeuronRobotics/nrjavaserial/files/2230388/hs_err_pid9628.log)

**Comment by madhephaestus** [comment]
check 3.19.0 to see if bug persists
