### ISSUE TITLE
android 4.3.0, testRead returns false?

### ISSUE THREAD

**Issue by tomato0127** [NeuronRobotics/nrjavaserial#140]
![image](https://user-images.githubusercontent.com/25834632/54400538-47197900-46fe-11e9-9b84-e9885b11a568.png)
Permission opened.

**Comment by madhephaestus** [comment]
yeah i am not aware of this working on android because of the permissions in the kernel of serial ports. If you know some way around that it should *just work* assuming the phones architecture is supported in the list of compile targets.
