### ISSUE TITLE
commons-net in maven dependencies

### ISSUE THREAD

**Issue by t5keeper** [NeuronRobotics/nrjavaserial#142]
Maven artifact

```
    <dependency>
      <groupId>com.neuronrobotics</groupId>
      <artifactId>nrjavaserial</artifactId>
      <version>3.15.0</version>
    </dependency>
```

Has dependency with scope compile.

```
    <dependency>
      <groupId>commons-net</groupId>
      <artifactId>commons-net</artifactId>
      <version>3.3</version>
      <scope>compile</scope>
    </dependency>
```

Which actually not used. Please remove it.

**Comment by wborn** [comment]
Looks like some of the rfc2217 classes depend on it, e.g.:

https://github.com/NeuronRobotics/nrjavaserial/blob/e06ed10e23284c36d19225b907e0b7a3b2736833/src/main/java/gnu/io/rfc2217/TelnetSerialPort.java#L69-L74
