### ISSUE TITLE
SerialInputStream does not throw IOException

### ISSUE THREAD

**Issue by t5keeper** [NeuronRobotics/nrjavaserial#143]
gnu.io.RXTXPort$SerialInputStream.read(byte[]) does not throws IOException when called on closed port.

**Comment by t5keeper** [comment]
gnu.io.RXTXPort$SerialInputStream.write(byte[]) has the same problem.

**Comment by Gerry33** [comment]
Same here: 
Reading on a removed device does throw lots of errors "Error 0x5 at src/windows/termios.c(2725): Access denied", but no Exception to catch

**Comment by madhephaestus** [comment]
Use the https://github.com/NeuronRobotics/nrjavaserial/releases/tag/5.0.3-prerelease nrjavaserial-5.0.3-pre.jar and this code example:

https://github.com/NeuronRobotics/nrjavaserial/blob/issue75-serialEventExitsOnHardwareLoss/test/src/test/ReadTest.java#L39

to detect when the hardware is disconnected.
