### ISSUE TITLE
how to encode byte read from com port

### ISSUE THREAD

**Issue by jrajauriya** [NeuronRobotics/nrjavaserial#149]
we are using jSerialComm library. we read byte from com port. but we are not able to encoded byte.

			```
        public static void main(String[] args) {
		SerialPort comPort = SerialPort.getCommPort("COM1");
		comPort.openPort();		
		comPort.setComPortParameters(9600, 8, 1, SerialPort.NO_PARITY);
		reading_bytes(comPort);
	}

          public static void reading_bytes(SerialPort comPort){		
		comPort.addDataListener(new SerialPortDataListener() {
			@Override
			public int getListeningEvents() {
				return SerialPort.LISTENING_EVENT_DATA_AVAILABLE;
			}

			@Override
			public void serialEvent(SerialPortEvent event) {
				if (event.getEventType() != SerialPort.LISTENING_EVENT_DATA_AVAILABLE)
					return;
				byte[] readBuffer = new byte[comPort.bytesAvailable()];
				int numRead = comPort.readBytes(readBuffer, readBuffer.length);
				System.out.println("Read " + numRead + " bytes.");
				for (byte b : readBuffer)
					System.out.print((int) b + ",");
				System.out.println();
			}
		});		
	}

and we got following output::
```
Read 14 bytes.
9,25,35,6,-20,73,-19,-64,33,62,108,-8,116,-2,
Read 0 bytes.

Read 14 bytes.
58,124,28,25,14,-58,24,62,-26,116,-96,7,7,-35,
Read 0 bytes.

Read 14 bytes.
3,6,15,54,59,-116,25,15,15,29,-125,6,-104,-16,
Read 0 bytes.

Read 14 bytes.
-48,-74,-60,100,-122,6,6,6,14,14,14,6,6,6,
Read 0 bytes.
.
.
.

**Comment by mizoguch-ken** [comment]
How about changing from
```
System.out.print((int) b + ",");
```
to
```
System.out.print((char) b + ",");
```

**Comment by mizoguch-ken** [comment]
I think that byte data and expected value do not match.
Is the communication setting correct?

**Comment by jrajauriya** [comment]
yes, we set the parameters `comPort.setComPortParameters(9600, 8, 1, SerialPort.NO_PARITY);` according to machine manual.

**Comment by mizoguch-ken** [comment]
Is it possible to get the actual settings instead of the manual?

**Comment by jrajauriya** [comment]
@mizoguch-ken yes it is possible, we got same output from com port to without set baud rate, data bits and parity.

**Comment by mizoguch-ken** [comment]
From the expected results, I think it is probably a LIS Interface.
If so, Can I view Configure LIS settings with DM Configuration Tool?

**Comment by madhephaestus** [comment]
not an issue in the library, closing
