### ISSUE TITLE
Compile for  MIPs  Architecture

### ISSUE THREAD

**Issue by ricardojlrufino** [NeuronRobotics/nrjavaserial#15]
Hello, I have been unsuccessfully trying to compile for MIPS architecture. 
I actually know very little C / Makefiles. 

The goal is to generate a lib for OpenWRT 

The guide we got was normal compile codes: 
http://www.componentality.com/res/Step-By-Step-Instruction-To-Run-Apps-On-FlexRoad-HW.en.pdf 

I've managed to run inside the router JamVM: 
wiki.openwrt.org/toh/tp-link/tl-mr3020 

Now we need to get access the serial port. 
This can be done with LUA: 
http://www.ediy.com.my/index.php/blog/item/40-send-message-to-serial-port-or-router-using-lua 

Why not Java?!

**Comment by madhephaestus** [comment]
stale closing
