### ISSUE TITLE
example program does not run

### ISSUE THREAD

**Issue by Reissner** [NeuronRobotics/nrjavaserial#159]
I think the example from the readme shall compile. 
For example the for loop misses blanks to compile. 

```
	for (String s : NRSerialPort.getAvailableSerialPorts()) {
	    System.out.println("Availible port: "+s);
	    //port=s;
	}
```

but there are other issues. 
Maybe a class and a main method around would be better.

**Comment by madhephaestus** [comment]
the example from the readme is for running in a groovy script to test. If you want it in a java class you do need to add a class encapsulation and a main method.

**Comment by Reissner** [comment]
ah i see... sorry.. 

i found other point: 
`char b = (char)ins.read()` i had to insert the cast.
