### ISSUE TITLE
nrjavaserial-3.9.2 fails on RHEL 5.8 (Tikanga) 64-bit

### ISSUE THREAD

**Issue by moberhuber** [NeuronRobotics/nrjavaserial#16]
Trying to use nrjavaserial-3.9.2 on a Redhat Enterprise Linux 5.8 machine (64-bit), we see this:
...
java.lang.UnsatisfiedLinkError: /tmp/libNRJavaSerial_uwe_0/libNRJavaSerial.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/libNRJavaSerial_uwe_0/libNRJavaSerial.so)
...
Which makes me wonder ... on what machine(s) is nrjavaserial compiled, and by whom ? I tried building myself on the RHEL 5.8 machine and the native build seems good but the Java part fails with compile errors ("annotations are only available if source level is 5.0"). I'm willing to help, but an incomplete build leaves me a bit unsure ...

**Comment by MrDOS** [comment]
@moberhuber #37 rebuilt the Linux binaries under glibc 2.5, a process I'm hoping to replicate going forward. Can you try the [latest release](https://github.com/NeuronRobotics/nrjavaserial/releases/tag/3.11.0) and let us know if it works a little better?

> on what machine(s) is nrjavaserial compiled, and by whom ?

Honestly, it is a little sporadic. @madhephaestus does the lion's share of the work on this project in general, including compilation of Windows natives and the Java code. I've built OS X natives the last couple times they've needed doing and as mentioned, Linux natives have most recently been contributed by @doychin. Which is a pretty hard-to-orchestrate way to run a railroad. Last year I started pursuing a “single source of truth” build environment (#19) and succeeded in identifying how I wanted to do it, but I ran out of free time before getting it implemented. I'm hoping to take another stab at it soon.
