### ISSUE TITLE
Better build infrastructure

### ISSUE THREAD

**Issue by MrDOS** [NeuronRobotics/nrjavaserial#19]
In light of the number of issues that have to do with binaries (#3, #8, #14, #17), I'd like to set up a publicly-accessible build server which periodically fetches the latest source and builds Linux, Windows, and possibly MacOS X natives, builds the Java source, and puts them all in a `jar`. @madhephaestus, as the man in charge, would you have any objection to this?

**Comment by MrDOS** [comment]
[This author](http://simongrondin.name/?p=394) came to the conclusion that the most portable binaries are those that ship with copies of all the libraries with which they link. Not sure I'm a fan of that solution. Related discussion revealed some information on [symbol versioning in glibc](https://www.kernel.org/pub/software/libs/glibc/hjl/compat/) which may be useful, though.

**Comment by MrDOS** [comment]
Cross-compilation with glibc targeting is going to be more pain than it's worth for Linux, I think. I'm going to take another stab at this with QEMU system emulation. I'll use Debian Etch ([glibc 2.3.6](http://archive.debian.net/source/etch/glibc)) as my target for i386/amd64/ppc and Lenny ([glibc 2.7](http://archive.debian.net/source/lenny/glibc)) for armel. I'd like to use Wheezy ([glibc 2.13](https://packages.debian.org/wheezy/glibc-2.13-1)) for armhf, but it [targets ARMv7](https://wiki.debian.org/ArmPorts) and I'd like an ARMv6 hardfloat binary (mainly to support the Raspberry Pi). This may mean cross-compiling from Wheezy or even building an emulator image on [Raspbian](http://www.raspbian.org/); I'll cross that bridge when I get there.

**Comment by MrDOS** [comment]
I built an ARMv5 binary in a QEMU image (using the `versatilepb` machine type and Debian Lenny) and it worked properly on real hardware. The disk image is now 489MB, and is currently using 128MB RAM. I'll see if it will work with less – 64MB should be OK.

We will need:

* ARMv5
* ARMv6
* ARMv6 hardfloat
* ARMv7
* ARMv7 hardfloat
* PPC
* i386
* AMD64

Simple extrapolation says we need ~4GB disk space and 512MB RAM to pull this off, assuming the base install size is similar for all platforms (it should be) and the RAM usage doesn't go up significantly for AMD64. The current build machine instance has 1GB RAM total and currently idles at ~300MB used, and 15GB disk space with the base OS using ~4.4GB of that, so we've got capacity to implement this sort of scheme.

**Comment by MrDOS** [comment]
Here's a more lightweight approach: `qemu-user-static` + `binfmt-support` + `debootstrap` gets me a chroot environment for an older system that I can call into without the overhead of a constantly running virtual machine. It's also [a fairly automatable setup](http://www.hellion.org.uk/blog/posts/foreign-chroots-with-schroot-and-qemu/). (Those steps are steps similar to, but not entirely like what we'll want. We've got no use for `sbuild`, but [`schroot`](https://wiki.debian.org/Schroot) sounds super useful.) The fly in the ointment: figuring out the permissions to do this without granting root access to the build system.

**Comment by madhephaestus** [comment]
Hmm, is this something that TravisCI could do?

**Comment by MrDOS** [comment]
Someone else is using [basically the same technique](https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html) to test on Raspian, but I don't like how they have to rebuild the `chroot` environment from scratch every time a test is kicked off. It's succeptable to failure should the OS repository experience an outage, and burning through (what would be for us) couple gigabytes of both Travis' and the mirror's bandwidth seems a little unscrupulous. Not to mention that it would actually time out: that post indicates a build took 40 minutes for them, which would be multiplied by 8 for us, putting us several times over the [50-minute maximum](https://github.com/travis-ci/travis-ci/issues/1362) before being killed, 

What we could do is pre-build the chroot environments and store them (compressed) on S3 or something (which would cost probably no more than a few cents per month; much less than I'm paying for the current build server), thereby reducing the setup phase to a fetch + unpack operation. I'll pursue this option. I'd rather use Travis if we can because of its [out-of-box](https://docs.travis-ci.com/user/pull-requests/) [integrations](https://docs.travis-ci.com/user/deployment/releases/).

**Comment by MrDOS** [comment]
I'm going to try to get back to this Soon® (“within the next two years at least, I promise!”). I've ordered three Raspberry Pis (B+/2/3) with the intent of automating native testing of the ARM builds.

**Comment by madhephaestus** [comment]
Awesome @MrDOS Thank you!

**Comment by madhephaestus** [comment]
I am still interested in this :)

**Comment by wborn** [comment]
I've been building nrjavaserial for openHAB using Docker with this [nrjavaserial-builder](https://github.com/wborn/nrjavaserial-builder/). It's using an Ubuntu 18.04 base image for that (see [Dockerfile](https://github.com/wborn/nrjavaserial-builder/blob/master/Dockerfile)). I still need to update it so it uses the built-in lockfile instead of [disabling them](https://github.com/wborn/nrjavaserial-builder/blob/326a8163c7ccd5120c7852a0e23299f1b810c812/entrypoint.sh#L8-L10). :wink: This way it's easy to compile the libraries on any host without the overhead of a VM in a reproducible way. With some adaptations it can also be used in this repo. I also use Travis CI with this [.travis.yml](https://github.com/wborn/nrjavaserial-builder/blob/master/.travis.yml) to check that everything still [builds](https://travis-ci.com/github/wborn/nrjavaserial-builder/builds).

**Comment by MrDOS** [comment]
> 2017-03-01: “within the next two years at least, I promise!”

2020-05-13: Ha, ha, ha.

> I am still interested in this :)

Believe me, I am too. Rather than try to lug around decades-old native code, though, I am trying to assess feasibility of porting to native Java and leveraging JNA. It will entail a lot of effort, but I don't have much else going on right now, and if it can work, then we can sidestep the natives and all the difficulties they bring.

@wborn, that's a great approach. If my JNA investigations prove fruitless, then I'd love to get your setup merged.
