### ISSUE TITLE
No native libs in apk

### ISSUE THREAD

**Issue by doit-ceo** [NeuronRobotics/nrjavaserial#190]
Hello, I'm trying to use NR as alternative for the rxtx old java lib, works fine in Linux, but in Android ,I'm having a hard time and after tracking the problem I found that my apk is getting built WITHOUT the native libs for linux/android !

Check the screenshot below and as you can see, Android Studio only packages Windows and OSX ! I tried everything including disabling proguard without any luck !

Thanks in Advance 

![Selection_587](https://user-images.githubusercontent.com/8027780/84574227-b375a300-adad-11ea-8a7e-f5ae73618c9e.png)

**Comment by madhephaestus** [comment]
there is no future Android support for non rooted phones. We did not continue to include the new android architectures since access to serial hardware was eliminated using permissions changed in android 4.x
