### ISSUE TITLE
short select() timeout causes MonitorThread CPU consumption

### ISSUE THREAD

**Issue by berndpfrommer** [NeuronRobotics/nrjavaserial#22]
using nrjavaserial-3.8.8, I'm seeing significant CPU consumption on low-end (atom) CPUs due to the RXTX MonitorThread being busy, although no EventListeners are attached to the port.
I believe this is due to the eventLoop() in SerialImp.c having a fairly short timeout on the select() call:

                        do {
				eis.ret = SELECT( eis.fd + 1, &eis.rfds, NULL, NULL,
					&eis.tv_sleep );
			} while (eis.ret < 0 && errno==EINTR);

The eis.tv_sleep is set to only 1000usec in intialise_event_info_struct():

	if (eis->fd < FD_SETSIZE && eis->fd > 0) {
		FD_SET( eis->fd, &eis->rfds );
		eis->tv_sleep.tv_sec = 0;
		eis->tv_sleep.tv_usec = 1000;
		eis->initialised = 1;
		return( 1 );
	} else {
		// you can reduce this limitation only with migration to epool or something like that.
	}

Which should cause the thread to wake up 1000 times per second, although no listener is attached.

Any suggestions on how to fix this?

**Comment by berndpfrommer** [comment]
closing this since a workaround exists.

**Comment by MrDOS** [comment]
@berndpfrommer We've recently incremented the sleep time to 100ms as suggested and it worked out quite well (#36). There's a pull request open (#48) with the new binaries included in its branch. If you're still involved in any projects using NRJavaSerial, we'd really appreciate it if you could confirm that they behave as expected. Either way, thanks for digging as deeply into this as you did.
