### ISSUE TITLE
Custom port names [linux]

### ISSUE THREAD

**Issue by maggu2810** [NeuronRobotics/nrjavaserial#23]
Hello!

If I want to use an udev rule to specify a fixed name for a serial interface, I have to use "gnu.io.rxtx.SerialPorts" or "gnu.io.SerialPorts" to add this port to the known ports.
Internally RXTXCommDriver is using the addSpecifiedPorts method to add ports to the list (read from the system property).
For example:

<pre>
addSpecifiedPorts("/dev/ttyMyCustomName0:/dev/ttyMyCusomName1", CommPortIdentifier.PORT_SERIAL);
</pre>

If I would like to use the library, I could do something similar to (very simplified):

<pre>
final CommPortIdentifier portIdentifier = CommPortIdentifier.getPortIdentifier(device);
final CommPort commPort = portIdentifier.open(id, TIMEOUT_MS_WAIT_FOR_OPEN);
final SerialPort serialPort = (SerialPort) commPort;
</pre>

This will fail if device is a custom device name and not set using the system property.

Will it be able, to add a public method that grant us to add some user specified devices.

<pre>
RXTXCommDriver.addCustomPort(device, CommPortIdentifier.PORT_SERIAL);
</pre>

or

<pre>
CommPortIdentifier.addCustomSerialPort(device);
</pre>

The implementation could check, if the device is already added (return true) and will use (as already done for system property) a testRead to test the device (return true is succeeded, otherwise false). So a return of true, signals I could use that device.

Are there some architectural problems or security risks?

**Comment by andyrozman** [comment]
I think, easiest way would be to add it to RXTXCommDriver, like you said:

RXTXCommDriver.addCustomPortPrefix(portPrefix, CommPortIdentifier.PORT_SERIAL);

and then this custom port prefixes would be added to CandidatePortPrefixes in method   registerScannedPorts.

@madhephaestus, @maggu2810: What do you think about that solution?

**Comment by maggu2810** [comment]
@andyrozman Hi, as you can see my comment is rather old ("Oct 16, 2014"). I don't know the nrjavaserial code base. Sorry
