### ISSUE TITLE
Known issues with Windows 11?

### ISSUE THREAD

**Issue by bengtmartensson** [NeuronRobotics/nrjavaserial#245]
Are there any known issues with Windows 11, version 22H2 to be exact? Differently put, can anyone confirm that nrjavaserial works with said OS?

The reason I ask is [this issue](https://github.com/bengtmartensson/IrScrutinizer/discussions/499).

**Comment by MrDOS** [comment]
Looks like the original reporter of the issue on your project has resolved the issue by swapping driver versions, so I'm going to close this issue.

FWIW, I have not explicitly tested this project with Windows 11, nor am I aware of anyone else having done so; however, I'd be very surprised if there were meaningful changes to serial ports between Windows 10 and 11. Serial ports are not exactly a fast-moving part of any OS these days!

Thanks for pointing us at the issue regardless, if only so we have a good recommendation for anyone else with the same problem.
