### ISSUE TITLE
no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver

### ISSUE THREAD

**Issue by rpawlitzek** [NeuronRobotics/nrjavaserial#25]
Hello everyone:

I use the nrjavaserial-3.9.3.jar file in an Eclipse project and I get the following error message: 

java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Port: COM7
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
    at java.lang.ClassLoader.loadLibrary(Unknown Source)
    at java.lang.Runtime.loadLibrary0(Unknown Source)
    at java.lang.System.loadLibrary(Unknown Source)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
    at ch.ntb.inf.repower.TwoWaySerialComm.main(TwoWaySerialComm.java:102)
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class gnu.io.CommPortIdentifier
    at ch.ntb.inf.repower.TwoWaySerialComm.connect(TwoWaySerialComm.java:18)
    at ch.ntb.inf.repower.TwoWaySerialComm.main(TwoWaySerialComm.java:114)

What do I have to do to resolve this error? 

Rene

**Comment by sambsa** [comment]
I am using windows 8.1, 64 bit, I also having the same eroor,
I have configured RXTX as follows for running my application in CMD
Copied rxtxParallel.dll and rxtxSerial.dll inside C:\Program Files\Java\jdk1.8.0_25\jre\bin
Copied RXTXcomm.jar inside C:\Program Files\Java\jdk1.8.0_25\jre\lib\ext

Error is like foolows:

java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while
loading gnu.io.RXTXCommDriver
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: no rxtxSerial in
java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)

Please help buddys!!

**Comment by madhephaestus** [comment]
Did you try the instructions here: http://mytechblog.com/tutorials/arduino/install-arduino-drivers-on-windows-8/ ? This issue was closed because it was a Windows-Device Driver issue, not a Java serial issue. 
You seem to be not using NRJavaSerial, and are using the original RXTXcomm. In fact if you are using *anything* with RXTX in it, or even have it on the disk in the wrong place, our library will not work the way you want. We packaged all the .dll's into the jar and it extracts them at runtime.

**Comment by arachchi** [comment]
I have the same issue with Linux. Please guide me to solve this problem.

**Comment by MrDOS** [comment]
This issue was closed a long time ago. If none of the solutions mentioned here solve the issue for you, please create a new issue and in its description, answer _all_ of the questions that @madhephaestus asked while trying to diagnose the problem here.

**Comment by arachchi** [comment]
Thank you.

Nuran Kasthuriarachchi
Undergraduate,
Computer Science and Engineering,
University of Moratuwa.

**Comment by ShyamBarange** [comment]
I am using windows 8.1, 64 bit, I also having the same eroor,
I have configured RXTX as follows for running my application in NetBeans IDE
Copied rxtxParallel.dll and rxtxSerial.dll inside C:\Program Files\Java\jdk1.8.0_25\jre\bin
Copied RXTXcomm.jar inside C:\Program Files\Java\jdk1.8.0_25\jre\lib\ext

when i run my java code  Error is like This:

java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while
loading gnu.io.RXTXCommDriver

I want to read NMEA data coming from GPS device. But i have stucked in the middle and can not even read the Port.

anyone with the solution? please help

**Comment by pcarmona79** [comment]
@ShyamBarange I think you must copy rxtxSerial.dll to C:\Program Files\Java\jdk1.8.0_25\jre\lib\amd64. In this directory you will found another JNI dlls.

**Comment by MrDOS** [comment]
@pcarmona79 Please don't ever, _ever_ place third-party DLLs in the JDK directory, regardless of the source! That is just asking for trouble.

@ShyamBarange, why are you using `rxtxParallel.dll` and `rxtxSerial.dll`? These are parts of the original RXTX project and are not used by NRJavaSerial. In fact, the use of NRJavaSerial requires no external components from RXTX and their presence is likely to confuse the JRE leading to errors like this one. To use NRJavaSerial in your project, you should only have to download the [latest JAR release](https://github.com/NeuronRobotics/nrjavaserial/releases) and add it to your classpath. I don't use NetBeans but this should simply entail creating a `lib` folder inside your project root, placing our JAR there, and [adding the JAR as a run-time library](http://stackoverflow.com/questions/4879903/how-to-add-a-jar-in-netbeans).

**Comment by DeepzSandra** [comment]
I’m using this code and I’m trying to use it to start RXTX with Arduino. I get the following compile errors:
C:\Users\cwc\java>java SerialTest.java
Exception in thread “main” java.lang.NoClassDefFoundError: SerialTest/java
Caused by: java.lang.ClassNotFoundException: SerialTest.java
 at java.net.URLClassLoader$1.run(Unknown Source)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(Unknown Source)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
 at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: SerialTest.java. Program will exit.
I followed these directions:
Windows 64-bit
RXTXcomm.jar goes in \jre\lib\ext 
rxtxSerial.dll goes in \jre\bin
Please any body help!!!!!

**Comment by pagalasoujanya** [comment]
i'm using datalogger, sending request and responses from the serialport using RXTX library in Linux 14.04 i'm getting this error

java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "main" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
	at readingports.ReadingPorts.main(ReadingPorts.java:39)
/home/polmon/.cache/netbeans/8.1/executor-snippets/run.xml:53: Java returned: 1
BUILD FAILED (total time: 0 seconds)

**Comment by Udara91** [comment]
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class gnu.io.RXTXVersion
	at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
	at vdf.Dispaly.StartDisplay(Dispaly.java:33)
	at vdf.Dispaly.main(Dispaly.java:160)

**Comment by MrDOS** [comment]
Hi @Udara91, this issue has been untouched for five years. Please create a new issue and include:

* the version of Java you're using (`java -version`),
* the version of NRJavaSerial you're trying to use,
* some details about the environment you're running your program in (from within an IDE, e.g., Eclipse/IntelliJ IDEA? From the command line? What command are you using? Etc.), and
* some information about how your project is structured (Maven? Gradle? Just an IDE project?), and how you're including NRJavaSerial in your project.

**Comment by Ferhat1999Fb** [comment]
Bu hatayı alıyorum ne yapabilirim 

java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "main" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1122)
	at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
	at com.example.SerialClass.initialize(SerialClass.java:68)
	at com.example.Main.openAis(Main.java:1276)
	at com.example.Main.<init>(Main.java:294)
	at com.example.Main.main(Main.java:272)

**Comment by fwolter** [comment]
Hi @Ferhat1999Fb, this issue has been untouched for six years. Please create a new issue and include:

- the version of Java you're using (java -version),
- the version of NRJavaSerial you're trying to use,
- some details about the environment you're running your program in (from within an IDE, e.g., Eclipse/IntelliJ IDEA? From the command line? What command are you using? Etc.), and
- some information about how your project is structured (Maven? Gradle? Just an IDE project?), and how you're including NRJavaSerial in your project.

**Comment by jaimealbapastor** [comment]
> For windows 8 forward, the unsigned drivers for serial ports have been broken. This sounds like that problem. Try the uinstructions from here: http://mytechblog.com/tutorials/arduino/install-arduino-drivers-on-windows-8/

I'm sorry to reopen this @MrDOS , but the link you sent 8 years ago is no longer available. Do you know a similar site that could solve the problem ?
And thanks a lot for your past contribution, It helped me a lot.

**Comment by MrDOS** [comment]
I had started writing a nice reply but I decided against it. Please read [this comment](https://github.com/NeuronRobotics/nrjavaserial/issues/25#issuecomment-167131178), and if that doesn't solve your issue, please open [a new issue](https://github.com/NeuronRobotics/nrjavaserial/issues/new) with all the details I asked for three comments up.

I'm happy to help you, but please, _please_ (and this goes for everyone else reading this), _do not_ necro a closed, eight-year-old issue, even if it looks like it applies to you. You've just generated an e-mail notification to everyone who has historically participated in this thread, and that alone is pretty rude. But on top of it, in doing so, you've also ignored mine and Fabian's pleas to other, past posters to create new issues. I'm willing to spend my time helping you work through the problem. In exchange, please spend just a little bit of your own time to properly describe your problem in a new issue.
