### ISSUE TITLE
License information is missing in the repo

### ISSUE THREAD

**Issue by kaikreuzer** [NeuronRobotics/nrjavaserial#28]
I assume you make the code available under the LGPL 2.1 as this is how RXTX is licensed. You do not have any license header on additional classes such as https://github.com/NeuronRobotics/nrjavaserial/blob/master/nrjavaserial/src/main/java/gnu/io/NRSerialPort.java nor have you a LICENSE file in the root of the repo.

It would be great if you could add such a license information as this is suggested as a best practice on Github, see https://help.github.com/articles/open-source-licensing/.

Thanks!
Kai

**Comment by jason-s** [comment]
I second this, please add the license information so that it is very clear.

**Comment by MrDOS** [comment]
Thanks for bringing this up. You're right, this needs to be dealt with. It's compounded by the fact our [build definition marks our archives as Apache licensed](https://github.com/NeuronRobotics/nrjavaserial/blob/master/build.gradle#L147) which in turn gets exposed in the [Maven Central Repository](http://mvnrepository.com/artifact/com.neuronrobotics/nrjavaserial/3.11.0). We should be LGPL and I'll try to correct it before the next release.

The only twist I see is that we include [jvser](https://github.com/archiecobbs/jvser) which has even more uncertain licensing terms. @madhephaestus, have you spoken with the maintainer of that project about the licensing terms of including his project in this one?

**Comment by MrDOS** [comment]
Looking through the commit history, I see RFC 2217 support was added by @crea-doo. @crea-doo, can you speak to the licensing of the jvser project?

**Comment by crea-doo** [comment]
Looking at https://code.google.com/p/jvser/ the code license is Apache License 2.0. On the GitHub page (https://github.com/archiecobbs/jvser) no license is mentioned.

**Comment by maggu2810** [comment]
ping...

What is the license of source code of this repository?

**Comment by kaikreuzer** [comment]
> Looking at https://code.google.com/p/jvser/ the code license is Apache License 2.0. On the GitHub page (https://github.com/archiecobbs/jvser) no license is mentioned. In the file headers also no license is mentioned.

@archiecobbs As you are the author of that code, it is probably best if you help us here:
1. Can you confirm that https://github.com/archiecobbs/jvser is under Apache 2 license?
2. As you seem to be the only author/copyright holder of this code: Would you be willing to additionally provide it under LGPL 2.1 for this project here? This would help nrjavaserial to be under a single license, so that the code base here becomes easier to be maintained wrt licensing.

Would be awesome if you could give us this approval!

**Comment by archiecobbs** [comment]
@kaikreuzer  sure no problem. Project has been updated.

**Comment by kaikreuzer** [comment]
Excellent, many thanks for your quick response @archiecobbs!
I have adapted the file headers in https://github.com/NeuronRobotics/nrjavaserial/pull/126 accordingly, please let me know in case you do NOT agree to them (note the extra exception clause of the RXTX library).
