### ISSUE TITLE
What is the point of the “legacy” native libraries?

### ISSUE THREAD

**Issue by MrDOS** [NeuronRobotics/nrjavaserial#45]
The native resources include a whole bunch of libraries with “_legacy” in their names. What was the intent of these? Are they the original binaries imported from RXTX? The Makefile doesn't give any indication of how they're built, which makes me suspect they're more older versions than alternatives.

**Comment by madhephaestus** [comment]
yeah, they were the linux 2.x kernel versions from the original rxtx project

**Comment by MrDOS** [comment]
Ah, gotcha. I'll do some testing on older machines at some point with our newer libraries to see how they hold up. It might not be worth keeping them (but I'm loathe to toss them without knowing for sure that they're not necessary).
