### ISSUE TITLE
Cortex A8 libraries go unused

### ISSUE THREAD

**Issue by MrDOS** [NeuronRobotics/nrjavaserial#46]
[`OSUtil#isCortexA8()`](https://github.com/NeuronRobotics/nrjavaserial/blob/master/src/main/java/gnu/io/NativeResource.java#L231) is stubbed-out and not called from anywhere, so the A8 native libraries are a bit pointless at the moment. Could they just be included at the front of [the usual list of ARM libraries](https://github.com/NeuronRobotics/nrjavaserial/blob/master/src/main/java/gnu/io/NativeResource.java#L43)? Can anyone name a cheap/widespread piece of A8 hardware I can get my grubby mitts on to test this?

**Comment by MrDOS** [comment]
Looks like I can use this as an excuse to splurge on a [BeagleBone Black](http://beagleboard.org/BLACK).

**Comment by madhephaestus** [comment]
stale closing
