### ISSUE TITLE
Update Gradle build to use C dir for artifacts

### ISSUE THREAD

**Issue by madhephaestus** [NeuronRobotics/nrjavaserial#49]
The gradle build can be modified to point to a specific directory for its 'resources'. We should point it at the directory where the C compile places the artifacts so no symlinks or anything like that is needed.

**Comment by MrDOS** [comment]
Way ahead of you ;)

https://github.com/NeuronRobotics/nrjavaserial/blob/master/build.gradle#L27

**Comment by madhephaestus** [comment]
yes, yes you are way ahead, you're awesome!
