### ISSUE TITLE
Include OSGI Bundle-NativeCode?

### ISSUE THREAD

**Issue by markusheiden** [NeuronRobotics/nrjavaserial#55]
What about including the specification of the native libs for OSGI? I am not sure if I everything is correct, but my best guess is:

Bundle-NativeCode: 
 native/linux/ARM/libNRJavaSerial.so;
 native/linux/ARM/libNRJavaSerial_HF.so;
 native/linux/ARM/libNRJavaSerialv5.so;
 native/linux/ARM/libNRJavaSerialv6.so;
 native/linux/ARM/libNRJavaSerialv6_HF.so;
 osname=Linux; processor=ARM,
 
 native/linux/ARM_A8/libNRJavaSerial.so;
 native/linux/ARM_A8/libNRJavaSerial_legacy.so;
 osname=Linux; processor=???,
 
 native/linux/PPC/libNRJavaSerial.so;
 osname=Linux; processor=PowerPC,
 
 native/linux/x86_32/libNRJavaSerial.so;
 native/linux/x86_32/libNRJavaSerial_legacy.so;
 osname=Linux; processor=x86,
 
 native/linux/x86_64/libNRJavaSerial.so;
 native/linux/x86_64/libNRJavaSerial_legacy.so;
 osname=Linux; processor=x86-64,
 
 native/osx/libNRJavaSerial.jnilib;
 osname=MacOSX,
 
 native/windows/x86_32/libNRJavaSerial.dll;
 osname=Win32; processor=x86,
 
 native/windows/x86_64/libNRJavaSerial.dll;
 osname=Win32; processor=x86-64,
 
 *

**Comment by madhephaestus** [comment]
Yeah, and the ??? ones have been removed now because they were cruft leftover from a while back.
