### ISSUE TITLE
select uses 1000 microsecond timeout

### ISSUE THREAD

**Issue by mdeneen** [NeuronRobotics/nrjavaserial#6]
Why is this so short?

https://github.com/NeuronRobotics/nrjavaserial/blob/master/nrjavaserial/src/main/c/src/SerialImp.c#L4149

I believe that this effectively turns the select into polling with such a short timeout.  Can this number be increased, or am I not understanding how the event loop works?

**Comment by MrDOS** [comment]
No, your understanding of how the event loop works is correct. #22 [hypothesized](https://github.com/NeuronRobotics/nrjavaserial/issues/22#issuecomment-59205913) that RXTX originally used a 100ms timeout on the `select(2)` call, but I've been unable to locate whatever commit changed that. Either way, this has been increased again as of ea5c0965c69bac549bf2023eaff20082bf85f67e and #48.

Thanks for bringing this up.

**Comment by mdeneen** [comment]
Awesome!  I completely forgot that I opened this.
