### ISSUE TITLE
Duplicated ressource in distribution jar

### ISSUE THREAD

**Issue by gchauvet** [NeuronRobotics/nrjavaserial#68]
Some files (in meta-inf folder) are duplicated. When we want to use this library in a applet way, our JRE raise an exception because "LICENSE.txt" entry is duplicated in JAR file (this is not the single file).

**Comment by GitoMat** [comment]
I have the same issue. "jarsigner" cannot process the jar file. The command fails:
`$ jarsigner -keystore store.jks -signedjar output/nrjavaserial-3.11.0.jar input/nrjavaserial-3.11.0.jar keyalias`
`jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: META-INF/LICENSE.txt`

The file is included twice:
`unzip -l nrjavaserial-3.11.0.jar | grep LICENSE.txt`
`11358  2014-01-05 18:01   META-INF/LICENSE.txt`
`11560  2013-06-07 23:49   META-INF/LICENSE.txt`

**Comment by madhephaestus** [comment]
Let me know if that worked for you?

**Comment by GitoMat** [comment]
Yes, signing works now, but as I discovered it already worked before this commit as LICENCE.txt wasn't in the Jar anymore.
