### ISSUE TITLE
Error 0x1f at src/windows/termios.c(2360) PortInUse even that it isn't

### ISSUE THREAD

**Issue by maxlarsson** [NeuronRobotics/nrjavaserial#78]
We are encounter the follow error with any version of nrjavaserial (3.9 up to 2.12.0):
    Error 0x1f at src/windows/termios.c(2360): A device attached to the system is n...
which is raised when we open the port. We really checked for sure that the port isn't used by any other application. And other serial programs (not based upon nrjavaserial) can open the port without any problems.
The serial port is a emulated port by the USBCom Driver version 5.23.00 from a datalogic handheld scanner D9530 STD, which seems to be cause for the failure. We know that nrjavaserial and the USBCom Driver can work together from previously projects. But we don't access anymore to an older version of the USBCom driver. Thus is there a way to workaround it in nrjavaserial?

**Comment by madhephaestus** [comment]
driver issue
