### ISSUE TITLE
Blocking thread (Thread-0) on MacOS using maven dependency. 

### ISSUE THREAD

**Issue by aroramayank2002** [NeuronRobotics/nrjavaserial#87]
I am using only this much of code in public static void main:
`SerialConnector.serial = new NRSerialPort("/dev/tty.usbmodem1234", 9600);
serial.connect();
serial.disconnect();`

connect() method starts a thread (Thread-0) which doesn't terminate even after disconnect() or completion of main.

I tried to interrupt the thread but no luck.
Also if I connect and disconnect repeatedly the thread keeps incrementing.

I am testing on MacOSX EL Capitan 10.11.5 using maven dependency.

I am able to fetch data from the serial device connected to MAC though.

**Comment by madhephaestus** [comment]
dependant on #163

**Comment by madhephaestus** [comment]
check 5.0.0 please
